### ISSUE TITLE
Unexpected character '@'

### ISSUE THREAD

**Issue by jfernandogt** [loganfsmyth/babel-plugin-transform-decorators-legacy#31] opened 2016-05-16 17:33 UTC
Hello,

I have the error: Parsing error: Unexpected character '@'. I am not sure what is wrong.

the code is: 
import ui from 'redux-ui';
**@**ui({})

my configuration is:
{
  "parser": "babel-eslint",
  "extends": ["eslint:recommended", "plugin:react/recommended"],
  "env": {
    "es6": true,
    "browser": true,
    "node": true
  },
  "plugins": ["react"],
  "parserOptions": {
    "ecmaVersion": 6,
    "sourceType": "module",
    "ecmaFeatures": {
      "modules": true,
      "jsx": true
    }
  },
  "rules": {
    "eqeqeq": [2, "allow-null"],
    "jsx-quotes": 2,
    "react/display-name": 2,
    "react/jsx-curly-spacing": [2, "never"],
    "react/self-closing-comp": 2,
    "react/jsx-indent-props": [2, 2],
    "react/jsx-no-duplicate-props": 2,
    "no-console":0,
    "strict": 0
  }
}

I am using this plugins and presets:
presets: ["es2015", "react", "stage-0"],
"plugins": ["babel-plugin-transform-decorators-legacy", "transform-runtime"]

**Comment by ascariandrea** [comment] 2016-05-17 10:22
👍

**Comment by loganfsmyth** [comment] 2016-05-17 16:27
Duplicate of https://github.com/babel/babel-eslint/issues/313.

This was a regression due to a change in ESLint.

**Closed as completed by loganfsmyth** 2016-05-17 16:27 UTC
